### PR TITLE
Fixes #318: Do not retry containers for which gathering tcp socket information failed once

### LINKED ISSUE #318: Connbeat triggers docker memory leak on docker containers without 'cat' executable
Introduction:
The docker daemon suffers from a memory leak, as described here:

https://forums.docker.com/t/docker-engine-leaks-memory-when-doing-a-docker-exec-on-a-non-existing-command/33820

Unfortunately, connbeat triggers this leak a lot when enabled on a kubernetes cluster on coreos, making machines going OOM in 30 minutes.

The cause is that connbeat tries to run the 'cat' executable on /pause containers from kubernetes, which don't have that executable. Connbeat handles this well, but as you can see in the above bug report, dockerd will leak.

Reproduce:
> Run a linux dockerd version as specified in the docker bugticket (https://coreos.com/os/docs/latest/booting-on-virtualbox.html for example)
> docker run -d gcr.io/google_containers/pause-amd64:3.0 /pause
> Start connbeat with docker enabled

Observe:
Machine going OOM

Expected:
Not going OOM

Although this is a docker issue, this issue is hitting older and 'stable' versions of docker, so I think we should work around this from connbeat.

### PR DESCRIPTION
**Pull request by craffit**
This fixes https://github.com/raboof/connbeat/issues/318.

As a solution (workaround) to the reported issue I choose to not retry gathering tcp information on docker containers when it failed once. This circumvents the repeated leaking when exec commands fail.

### CODE REVIEW

File: sockets/docker/docker.go [hunk 1]
```diff
@@ -115,10 +123,9 @@ func (p *Poller) pollCurrentConnectionsFor(container docker.APIContainers, file
 	if err != nil {
 		return err
 	}
-	var stdout, stderr bytes.Buffer
+	var stdout bytes.Buffer
```
Comment (raboof) [inline sockets/docker/docker.go]: Hmm, where does stderr go? does it inherit from the parent process when it's not bound?

Comment (craffit) [inline sockets/docker/docker.go]: It is discarded by go dockerclient if I understand the code correctly

Comment (raboof) [inline sockets/docker/docker.go]: hmm ideally it'd end up _somewhere_... but since this is a pretty narrow use case perhaps it's OK to discard it
